//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmMoveit
{
    [Serializable]
    public class BehaviorTreeMsg : Message
    {
        public const string k_RosMessageName = "xarm_moveit/BehaviorTree";
        public override string RosMessageName => k_RosMessageName;

        public string retrieve_root;
        public TreeNodeMsg[] First_layer;
        public TreeNodeMsg[] Second_layer;
        public TreeNodeMsg[] Third_layer;

        public BehaviorTreeMsg()
        {
            this.retrieve_root = "";
            this.First_layer = new TreeNodeMsg[0];
            this.Second_layer = new TreeNodeMsg[0];
            this.Third_layer = new TreeNodeMsg[0];
        }

        public BehaviorTreeMsg(string retrieve_root, TreeNodeMsg[] First_layer, TreeNodeMsg[] Second_layer, TreeNodeMsg[] Third_layer)
        {
            this.retrieve_root = retrieve_root;
            this.First_layer = First_layer;
            this.Second_layer = Second_layer;
            this.Third_layer = Third_layer;
        }

        public static BehaviorTreeMsg Deserialize(MessageDeserializer deserializer) => new BehaviorTreeMsg(deserializer);

        private BehaviorTreeMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.retrieve_root);
            deserializer.Read(out this.First_layer, TreeNodeMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.Second_layer, TreeNodeMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.Third_layer, TreeNodeMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.retrieve_root);
            serializer.WriteLength(this.First_layer);
            serializer.Write(this.First_layer);
            serializer.WriteLength(this.Second_layer);
            serializer.Write(this.Second_layer);
            serializer.WriteLength(this.Third_layer);
            serializer.Write(this.Third_layer);
        }

        public override string ToString()
        {
            return "BehaviorTreeMsg: " +
            "\nretrieve_root: " + retrieve_root.ToString() +
            "\nFirst_layer: " + System.String.Join(", ", First_layer.ToList()) +
            "\nSecond_layer: " + System.String.Join(", ", Second_layer.ToList()) +
            "\nThird_layer: " + System.String.Join(", ", Third_layer.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
