//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmMoveit
{
    [Serializable]
    public class ExtrinsicsMsg : Message
    {
        public const string k_RosMessageName = "xarm_moveit/Extrinsics";
        public override string RosMessageName => k_RosMessageName;

        //  Cross-stream extrinsics: encodes the topology describing how the different devices are oriented
        public double[] rotation;
        //  Column - major 3x3 rotation matrix
        public double[] translation;
        //  Three-element translation vector, in meters

        public ExtrinsicsMsg()
        {
            this.rotation = new double[9];
            this.translation = new double[3];
        }

        public ExtrinsicsMsg(double[] rotation, double[] translation)
        {
            this.rotation = rotation;
            this.translation = translation;
        }

        public static ExtrinsicsMsg Deserialize(MessageDeserializer deserializer) => new ExtrinsicsMsg(deserializer);

        private ExtrinsicsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.rotation, sizeof(double), 9);
            deserializer.Read(out this.translation, sizeof(double), 3);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.rotation);
            serializer.Write(this.translation);
        }

        public override string ToString()
        {
            return "ExtrinsicsMsg: " +
            "\nrotation: " + System.String.Join(", ", rotation.ToList()) +
            "\ntranslation: " + System.String.Join(", ", translation.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
