//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmMoveit
{
    [Serializable]
    public class RGBDMsg : Message
    {
        public const string k_RosMessageName = "xarm_moveit/RGBD";
        public override string RosMessageName => k_RosMessageName;

        //  RGBD Message
        public Std.HeaderMsg header;
        public Sensor.CameraInfoMsg rgb_camera_info;
        public Sensor.CameraInfoMsg depth_camera_info;
        public Sensor.ImageMsg rgb;
        public Sensor.ImageMsg depth;

        public RGBDMsg()
        {
            this.header = new Std.HeaderMsg();
            this.rgb_camera_info = new Sensor.CameraInfoMsg();
            this.depth_camera_info = new Sensor.CameraInfoMsg();
            this.rgb = new Sensor.ImageMsg();
            this.depth = new Sensor.ImageMsg();
        }

        public RGBDMsg(Std.HeaderMsg header, Sensor.CameraInfoMsg rgb_camera_info, Sensor.CameraInfoMsg depth_camera_info, Sensor.ImageMsg rgb, Sensor.ImageMsg depth)
        {
            this.header = header;
            this.rgb_camera_info = rgb_camera_info;
            this.depth_camera_info = depth_camera_info;
            this.rgb = rgb;
            this.depth = depth;
        }

        public static RGBDMsg Deserialize(MessageDeserializer deserializer) => new RGBDMsg(deserializer);

        private RGBDMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.rgb_camera_info = Sensor.CameraInfoMsg.Deserialize(deserializer);
            this.depth_camera_info = Sensor.CameraInfoMsg.Deserialize(deserializer);
            this.rgb = Sensor.ImageMsg.Deserialize(deserializer);
            this.depth = Sensor.ImageMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.rgb_camera_info);
            serializer.Write(this.depth_camera_info);
            serializer.Write(this.rgb);
            serializer.Write(this.depth);
        }

        public override string ToString()
        {
            return "RGBDMsg: " +
            "\nheader: " + header.ToString() +
            "\nrgb_camera_info: " + rgb_camera_info.ToString() +
            "\ndepth_camera_info: " + depth_camera_info.ToString() +
            "\nrgb: " + rgb.ToString() +
            "\ndepth: " + depth.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
