//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmMoveit
{
    [Serializable]
    public class TreeNodeMsg : Message
    {
        public const string k_RosMessageName = "xarm_moveit/TreeNode";
        public override string RosMessageName => k_RosMessageName;

        public string node_name;
        public string parent;

        public TreeNodeMsg()
        {
            this.node_name = "";
            this.parent = "";
        }

        public TreeNodeMsg(string node_name, string parent)
        {
            this.node_name = node_name;
            this.parent = parent;
        }

        public static TreeNodeMsg Deserialize(MessageDeserializer deserializer) => new TreeNodeMsg(deserializer);

        private TreeNodeMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.node_name);
            deserializer.Read(out this.parent);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.node_name);
            serializer.Write(this.parent);
        }

        public override string ToString()
        {
            return "TreeNodeMsg: " +
            "\nnode_name: " + node_name.ToString() +
            "\nparent: " + parent.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
