//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmMoveit
{
    [Serializable]
    public class UnityImageMsg : Message
    {
        public const string k_RosMessageName = "xarm_moveit/UnityImage";
        public override string RosMessageName => k_RosMessageName;

        public int height;
        //  image height, that is, number of rows
        public int width;
        //  image width, that is, number of columns
        public byte[] data;
        //  actual matrix data, size is (h*w*c)

        public UnityImageMsg()
        {
            this.height = 0;
            this.width = 0;
            this.data = new byte[0];
        }

        public UnityImageMsg(int height, int width, byte[] data)
        {
            this.height = height;
            this.width = width;
            this.data = data;
        }

        public static UnityImageMsg Deserialize(MessageDeserializer deserializer) => new UnityImageMsg(deserializer);

        private UnityImageMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.height);
            deserializer.Read(out this.width);
            deserializer.Read(out this.data, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.height);
            serializer.Write(this.width);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "UnityImageMsg: " +
            "\nheight: " + height.ToString() +
            "\nwidth: " + width.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
