//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmMoveit
{
    [Serializable]
    public class DetectionServiceResponse : Message
    {
        public const string k_RosMessageName = "xarm_moveit/DetectionService";
        public override string RosMessageName => k_RosMessageName;

        public byte detect_number;
        public double[] rectangle;
        public Geometry.PoseMsg[] poses;
        public byte responseindex;

        public DetectionServiceResponse()
        {
            this.detect_number = 0;
            this.rectangle = new double[0];
            this.poses = new Geometry.PoseMsg[0];
            this.responseindex = 0;
        }

        public DetectionServiceResponse(byte detect_number, double[] rectangle, Geometry.PoseMsg[] poses, byte responseindex)
        {
            this.detect_number = detect_number;
            this.rectangle = rectangle;
            this.poses = poses;
            this.responseindex = responseindex;
        }

        public static DetectionServiceResponse Deserialize(MessageDeserializer deserializer) => new DetectionServiceResponse(deserializer);

        private DetectionServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.detect_number);
            deserializer.Read(out this.rectangle, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.poses, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.responseindex);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.detect_number);
            serializer.WriteLength(this.rectangle);
            serializer.Write(this.rectangle);
            serializer.WriteLength(this.poses);
            serializer.Write(this.poses);
            serializer.Write(this.responseindex);
        }

        public override string ToString()
        {
            return "DetectionServiceResponse: " +
            "\ndetect_number: " + detect_number.ToString() +
            "\nrectangle: " + System.String.Join(", ", rectangle.ToList()) +
            "\nposes: " + System.String.Join(", ", poses.ToList()) +
            "\nresponseindex: " + responseindex.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
