//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmMoveit
{
    [Serializable]
    public class ImageServiceRequest : Message
    {
        public const string k_RosMessageName = "xarm_moveit/ImageService";
        public override string RosMessageName => k_RosMessageName;

        public int servicenumber;

        public ImageServiceRequest()
        {
            this.servicenumber = 0;
        }

        public ImageServiceRequest(int servicenumber)
        {
            this.servicenumber = servicenumber;
        }

        public static ImageServiceRequest Deserialize(MessageDeserializer deserializer) => new ImageServiceRequest(deserializer);

        private ImageServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.servicenumber);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.servicenumber);
        }

        public override string ToString()
        {
            return "ImageServiceRequest: " +
            "\nservicenumber: " + servicenumber.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
