//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmMoveit
{
    [Serializable]
    public class ImageServiceResponse : Message
    {
        public const string k_RosMessageName = "xarm_moveit/ImageService";
        public override string RosMessageName => k_RosMessageName;

        public UnityImageMsg ugv_image;
        public UnityImageMsg robot_image;

        public ImageServiceResponse()
        {
            this.ugv_image = new UnityImageMsg();
            this.robot_image = new UnityImageMsg();
        }

        public ImageServiceResponse(UnityImageMsg ugv_image, UnityImageMsg robot_image)
        {
            this.ugv_image = ugv_image;
            this.robot_image = robot_image;
        }

        public static ImageServiceResponse Deserialize(MessageDeserializer deserializer) => new ImageServiceResponse(deserializer);

        private ImageServiceResponse(MessageDeserializer deserializer)
        {
            this.ugv_image = UnityImageMsg.Deserialize(deserializer);
            this.robot_image = UnityImageMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ugv_image);
            serializer.Write(this.robot_image);
        }

        public override string ToString()
        {
            return "ImageServiceResponse: " +
            "\nugv_image: " + ugv_image.ToString() +
            "\nrobot_image: " + robot_image.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
