//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmMoveit
{
    [Serializable]
    public class SamDetectionServiceResponse : Message
    {
        public const string k_RosMessageName = "xarm_moveit/SamDetectionService";
        public override string RosMessageName => k_RosMessageName;

        public double[] confidence;
        public int[] categorys;
        public Geometry.PoseMsg[] poses;
        public Geometry.PoseMsg[] zed_poses;
        public double[] angles;

        public SamDetectionServiceResponse()
        {
            this.confidence = new double[0];
            this.categorys = new int[0];
            this.poses = new Geometry.PoseMsg[0];
            this.zed_poses = new Geometry.PoseMsg[0];
            this.angles = new double[0];
        }

        public SamDetectionServiceResponse(double[] confidence, int[] categorys, Geometry.PoseMsg[] poses, Geometry.PoseMsg[] zed_poses, double[] angles)
        {
            this.confidence = confidence;
            this.categorys = categorys;
            this.poses = poses;
            this.zed_poses = zed_poses;
            this.angles = angles;
        }

        public static SamDetectionServiceResponse Deserialize(MessageDeserializer deserializer) => new SamDetectionServiceResponse(deserializer);

        private SamDetectionServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.confidence, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.categorys, sizeof(int), deserializer.ReadLength());
            deserializer.Read(out this.poses, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.zed_poses, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.angles, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.confidence);
            serializer.Write(this.confidence);
            serializer.WriteLength(this.categorys);
            serializer.Write(this.categorys);
            serializer.WriteLength(this.poses);
            serializer.Write(this.poses);
            serializer.WriteLength(this.zed_poses);
            serializer.Write(this.zed_poses);
            serializer.WriteLength(this.angles);
            serializer.Write(this.angles);
        }

        public override string ToString()
        {
            return "SamDetectionServiceResponse: " +
            "\nconfidence: " + System.String.Join(", ", confidence.ToList()) +
            "\ncategorys: " + System.String.Join(", ", categorys.ToList()) +
            "\nposes: " + System.String.Join(", ", poses.ToList()) +
            "\nzed_poses: " + System.String.Join(", ", zed_poses.ToList()) +
            "\nangles: " + System.String.Join(", ", angles.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
