//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmMoveit
{
    [Serializable]
    public class TriggerTwistResponse : Message
    {
        public const string k_RosMessageName = "xarm_moveit/TriggerTwist";
        public override string RosMessageName => k_RosMessageName;

        public double location;
        public string response_text;
        //  Service response indicating success or failure

        public TriggerTwistResponse()
        {
            this.location = 0.0;
            this.response_text = "";
        }

        public TriggerTwistResponse(double location, string response_text)
        {
            this.location = location;
            this.response_text = response_text;
        }

        public static TriggerTwistResponse Deserialize(MessageDeserializer deserializer) => new TriggerTwistResponse(deserializer);

        private TriggerTwistResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.location);
            deserializer.Read(out this.response_text);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.location);
            serializer.Write(this.response_text);
        }

        public override string ToString()
        {
            return "TriggerTwistResponse: " +
            "\nlocation: " + location.ToString() +
            "\nresponse_text: " + response_text.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
