//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmMoveit
{
    [Serializable]
    public class TriggerTwistRequest : Message
    {
        public const string k_RosMessageName = "xarm_moveit/TriggerTwist";
        public override string RosMessageName => k_RosMessageName;

        public double duration;
        //  Duration to send the Twist message (in seconds)
        public Geometry.TwistMsg twist_value;

        public TriggerTwistRequest()
        {
            this.duration = 0.0;
            this.twist_value = new Geometry.TwistMsg();
        }

        public TriggerTwistRequest(double duration, Geometry.TwistMsg twist_value)
        {
            this.duration = duration;
            this.twist_value = twist_value;
        }

        public static TriggerTwistRequest Deserialize(MessageDeserializer deserializer) => new TriggerTwistRequest(deserializer);

        private TriggerTwistRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.duration);
            this.twist_value = Geometry.TwistMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.duration);
            serializer.Write(this.twist_value);
        }

        public override string ToString()
        {
            return "TriggerTwistRequest: " +
            "\nduration: " + duration.ToString() +
            "\ntwist_value: " + twist_value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
