//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmMoveit
{
    [Serializable]
    public class UnitySaveResponse : Message
    {
        public const string k_RosMessageName = "xarm_moveit/UnitySave";
        public override string RosMessageName => k_RosMessageName;

        public int success;
        public string result;

        public UnitySaveResponse()
        {
            this.success = 0;
            this.result = "";
        }

        public UnitySaveResponse(int success, string result)
        {
            this.success = success;
            this.result = result;
        }

        public static UnitySaveResponse Deserialize(MessageDeserializer deserializer) => new UnitySaveResponse(deserializer);

        private UnitySaveResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.result);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "UnitySaveResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
