//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmMoveit
{
    [Serializable]
    public class UnitySaveRequest : Message
    {
        public const string k_RosMessageName = "xarm_moveit/UnitySave";
        public override string RosMessageName => k_RosMessageName;

        public int mode;
        public string foldername;
        public string chathistory;
        public string statistics;

        public UnitySaveRequest()
        {
            this.mode = 0;
            this.foldername = "";
            this.chathistory = "";
            this.statistics = "";
        }

        public UnitySaveRequest(int mode, string foldername, string chathistory, string statistics)
        {
            this.mode = mode;
            this.foldername = foldername;
            this.chathistory = chathistory;
            this.statistics = statistics;
        }

        public static UnitySaveRequest Deserialize(MessageDeserializer deserializer) => new UnitySaveRequest(deserializer);

        private UnitySaveRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
            deserializer.Read(out this.foldername);
            deserializer.Read(out this.chathistory);
            deserializer.Read(out this.statistics);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
            serializer.Write(this.foldername);
            serializer.Write(this.chathistory);
            serializer.Write(this.statistics);
        }

        public override string ToString()
        {
            return "UnitySaveRequest: " +
            "\nmode: " + mode.ToString() +
            "\nfoldername: " + foldername.ToString() +
            "\nchathistory: " + chathistory.ToString() +
            "\nstatistics: " + statistics.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
