//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmMoveit
{
    [Serializable]
    public class UnityDetectionServiceResponse : Message
    {
        public const string k_RosMessageName = "xarm_moveit/UnityDetectionService";
        public override string RosMessageName => k_RosMessageName;

        public double[] confidence;
        public Geometry.PoseMsg[] poses;

        public UnityDetectionServiceResponse()
        {
            this.confidence = new double[0];
            this.poses = new Geometry.PoseMsg[0];
        }

        public UnityDetectionServiceResponse(double[] confidence, Geometry.PoseMsg[] poses)
        {
            this.confidence = confidence;
            this.poses = poses;
        }

        public static UnityDetectionServiceResponse Deserialize(MessageDeserializer deserializer) => new UnityDetectionServiceResponse(deserializer);

        private UnityDetectionServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.confidence, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.poses, Geometry.PoseMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.confidence);
            serializer.Write(this.confidence);
            serializer.WriteLength(this.poses);
            serializer.Write(this.poses);
        }

        public override string ToString()
        {
            return "UnityDetectionServiceResponse: " +
            "\nconfidence: " + System.String.Join(", ", confidence.ToList()) +
            "\nposes: " + System.String.Join(", ", poses.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
